name: AirFidelity

options:
  bundleIdPrefix: com.vincehopf
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  defaultConfig: Release

packages:
  SimplyCoreAudio:
    url: https://github.com/rnine/SimplyCoreAudio
    from: 4.0.0
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    exactVersion: 2.8.1

targets:
  AirFidelity:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Resources
    dependencies:
      - package: SimplyCoreAudio
      - package: Sparkle
    info:
      path: Sources/Info.plist
      properties:
        LSUIElement: true
        NSMicrophoneUsageDescription: "AirFidelity needs microphone access to detect when your Mac's audio input changes. No audio is recorded."
        SUFeedURL: "https://vincehopf.github.io/AirFidelity/appcast.xml"
        SUPublicEDKey: "tmHJg3zGKt0wPIpA/IKBHOXIM2v/pGH9Qoqfl1bbhH4="
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.vincehopf.AirFidelity
    entitlements:
      path: AirFidelity.entitlements

  AirFidelityTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: AirFidelity
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: true
